project:
  type: website
  output-dir: docs

website:
  title: "Nick Bearman"
  site-url: https://nickbearman.github.io/
  description: "A blog on my teaching, open source GIS, travel and life"
  navbar:
    pinned: TRUE
    left:
      - href: index.qmd
        text: Home
      - training-courses.qmd
      - training-materials.qmd
      - consultancy.qmd
      - writing-presentations.qmd
      - blog.qmd
    right:
      - icon: rss
        href: blog.xml

format:
  html:
    css: styles.css
    theme: lumen
    toc: true


