project:
  type: website
  output-dir: docs

website:
  title: "Nick Bearman"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - training-courses.qmd
      - training-materials.qmd
      - consultancy.qmd
      - writing-presentations.qmd
      - blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

