---
  title: "Consultancy"
---

I can work with you to add geospatial analysis to your project and to develop your geospatial analysis toolset. I have worked with academics, universities, private sector and public sector organisations, developing bespoke training, one-to-one tuition or project support to enable my clients to get the best from their geospatial data.

<!-- Emily / Uni of Birmingham -->

<!-- ### South West Coast Path -->


### Geospatial Analysis Capacity Building - University of Portsmouth

"Working with Nick has been really great. His classes and consultancy have been extremely professional and instrumental in rapidly upscaling our abilities in both geo-spatial analysis and in the R programming language. We are far more effective now than we were before our engagement with him. Thanks Nick!"

*Dr Ed Stoddard, Associate Professor in International Security and Dr Melita Lazell, Principal Lecturer in Global Political Economy and Associate Head (Research), School of Area Studies, History, Politics and Literature University of Portsmouth*

Images - RedBull, Netflix

<!--
### North Devon Biosphere & University of Exeter

- Carolyn / Exeter
    - what I did
    - outputs - report, code, plugins (ArcGIS and QGIS)

-->

### Admissions Dashboard - University of Westminster

“The work Nick has carried out has helped us to greatly enhance the way we work with schools. The dashboard he has helped us build allows us to quickly find points of collaboration as well as key demographic and student population data.”

*Dr Doug Specht, Senior Lecturer, Director of Teaching and Learning, School of Media and Communication, University of Westminster*

Screenshot

<!-- 14/09/2021, 2021-35-doug-specht-arcgis-online-dashboard -->



