---
  title: "Training Courses"
---

I offer a variety of training courses on GIS and spatial data, including introductory and advanced training using QGIS and R. My training is designed to both teach you about GIS itself and how to use the software to do make maps and perform spatial analysis.

My courses are constantly being developed to take advantage of the latest changes in QGIS and R. Below is a list of the courses coming up, and a link to sign up (where available). If you would like a course run for a group of you, then please [contact me](index.html) discuss your needs and for a quote.

If a course does not have a date, then please join my [mailing list](mailing-list.html) to hear when new dates are confirmed.

```         

- Kalvin testomonial
- Ed Stoddard / Plymouth
- one to one sessions
- grid of course options, with links to online material
- sign up to mailing list
```

"Nice balance of theory and practice. Also useful to learn what to look for if things go wrong. Content was flexible to include what might be useful for our work." Vickie, Analyst, Public Health Wales.

\<!-- <file:///C:/Users/nick/Documents/work/2022-37-public-health-wales-gis-training/feedback-forms.pdf> –\>

If you have any questions please do [contact me]() or email nick\@nickbearman.com if you have any questions.

|              | R                                                                                                                          | QGIS                                                                              |
|--------------|-----------------------------------|-----------------------|
| Introductory | [Introduction to Spatial Data and Using R as a GIS](#introduction-to-spatial-data-using-r-as-a-gis) 09/01/2024 CC          | [Introduction to QGIS: Understanding and Presenting Spatial Data]\* 09/01/2025 CC |
| Advanced     | [Confident Spatial Analysis and Statistics in R & GeoDa](#confident-spatial-analysis-and-statistics-in-r-geoda) 09/02/2025 | [Confident Spatial Analysis in QGIS]\* 09/01/2025                                 |

*\*often presented together as "Introduction to QGIS: Spatial Data and Spatial Analysis" over 4 half-day sessions.*

"I love having a workbook to go through, it's how I learn best. Also, perfect balance between presentation and practical work." Yes (with my name and affiliation) Harriet Ann Patrick PhD Researcher University of Sheffield

### Introduction to Spatial Data and Using R as a GIS {#introduction-to-spatial-data-using-r-as-a-gis}

<existing text>

\<text\>

### Confident Spatial Analysis and Statistics in R & GeoDa {#confident-spatial-analysis-and-statistics-in-r-geoda}

<existing text>

\<text\>

### Introduction to QGIS: Understanding and Presenting Spatial Data

\<text\>

### Confident Spatial Analysis in QGIS

\<text\>

### Introduction to QGIS: Spatial Data and Spatial Analysis

*This course is Introdudction to QGIS and Confidielt Spatial Analysis in QGIS run back to back.*

\<text\>

## Other Courses

I have also run a number of other courses, usually based on the four courses above and tweaked for a bespoke audience (examples include Public Health Wales, Essex Summer School, UEA International Development). If you are interested in a bespoke course, please Contact Me for a discussion and a quote.
