---
  title: "Installing Software - GeoDa"
---


We will be setting up GeoDa. Follow the instructions below, depending on your operating system.

## Windows 

- Open a web browser and go to [http://geodacenter.github.io/](http://geodacenter.github.io/).  
- Click **Download**.  
- Click **Download for Windows**.  
- Download **GeoDa 1.22.0.14 (1/30/2025)**. *Select the 64 bit version, unless you have a very old computer, or know that you need the 32 bit version*.  
- Run `GeoDa_1.22_win7+x64_Setup.exe` from within the zip file. 
- If Windows says "Windows protected your PC", it may have blocked installation. Choose **More info** and then **Run anyway** to install GeoDa. 
- Run through the program installation process.  


## Mac OSX

- Open a web browser and go to [http://geodacenter.github.io/](http://geodacenter.github.io/).  
- Click **Download**.  
- Click **Download for Mac**.  
- Download **GeoDa 1.22.0.14 (1/30/2025) for Mac OS X (Big Sur+)**. 
- Follow through the installation wizard.  

**Note the instructions at the bottom of the page:**

*Please note that you will get a warning message about this program coming from an unknown developer the first time you try to open it.*

*Use control-click and select open to open the program (instead of double click) and accept at the prompt. You will not be asked this again. However, in order for this to work, you need to set your Security & Privacy preferences to Mac App Store and identified developers; the default is Mac App store only, which will NOT WORK for GeoDa.*

<!-- 
## Linux/Ubuntu

- Open a web browser and go to http://www.qgis.org.  
- Click **Download Now**.  
- Expand the **Download for Linux** option.  
- Follow the instructions for the appropriate Linux distribution.  -->
<!-- add more to this section -->

You are good to go!

*This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License. To view a copy of this license, visit [http://creativecommons.org/licenses/by-sa/4.0/deed.en](http://creativecommons.org/licenses/by-sa/4.0/deed.en). The latest version of this is available from [https://nickbearman.github.io/installing-software/geoda](https://nickbearman.github.io/installing-software/geoda).*
